### ISSUE TITLE
wassup_bro status incorrectly returns running when bro is stopped

### ISSUE THREAD

**Issue by RyPeck** [panaman/puppet-bro#3]
The status check for `wassup_bro` is insufficient.

`broctl status` exit status is 0 even if the nodes have been stopped.

**Comment by panaman** [comment]
it appears that the issues in't with wassup_bro, but with bro_cron

I have a duplicate bro dir.
%x(/opt/bro/bro/bin/broctl status 2>&1)

I will get this fixed tonight.

**Comment by panaman** [comment]
bro path in bro_cron.erb file has been fixed
